# Generated by Django 4.1.5 on 2023-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_topic_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='creator',
            field=models.CharField(max_length=150),
        ),
    ]
