# Generated by Django 4.1.5 on 2023-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_topic_answers_topic_views_topic_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='viewers',
            field=models.JSONField(default={'viewed': []}),
        ),
    ]
