# Generated by Django 4.1.5 on 2023-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_topic_category_delete_topiccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
