# Generated by Django 4.1.5 on 2023-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_topic_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='users_voted',
            field=models.JSONField(default=list),
        ),
    ]
