# Generated by Django 4.1.5 on 2023-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_remove_comment_topic_comment_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comments',
        ),
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.ManyToManyField(blank=True, to='questions.comment'),
        ),
    ]
